
package com.bmc.atrium._2009._01.instances;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AtriumFault", targetNamespace = "http://atrium.bmc.com/2009/01/common")
public class AtriumFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.bmc.atrium._2009._01.common.AtriumFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AtriumFault(String message, com.bmc.atrium._2009._01.common.AtriumFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AtriumFault(String message, com.bmc.atrium._2009._01.common.AtriumFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bmc.atrium._2009._01.common.AtriumFault
     */
    public com.bmc.atrium._2009._01.common.AtriumFault getFaultInfo() {
        return faultInfo;
    }

}
