package com.metricstream.itgrc.atr.dao.vo;

// Generated Apr 30, 2016 1:40:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsItgBmcComputerSystem generated by hbm2java
 */
@Entity
@Table(name = "MS_ITG_BMC_COMPUTER_SYSTEM")
public class MsItgBmcComputerSystem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String instanceId;
	private String className;
	private String namespaceName;
	private String name;
	private String description;
	private String region;
	private String siteGroup;
	private String site;
	private String floor;
	private String room;
	private String confidentiality;
	private String integrity;
	private String department;
	private String ownerName;
	private String serialNumber;
	private String domain;
	private String availability;
	private String primaryCapability;

	public MsItgBmcComputerSystem() {
	}

	public MsItgBmcComputerSystem(String instanceId) {
		this.instanceId = instanceId;
	}

	public MsItgBmcComputerSystem(String instanceId, String className,
			String namespaceName, String name, String description,
			String region, String siteGroup, String site, String floor,
			String room, String confidentiality, String integrity,
			String department, String ownerName, String serialNumber,
			String domain, String availability, String primaryCapability) {
		this.instanceId = instanceId;
		this.className = className;
		this.namespaceName = namespaceName;
		this.name = name;
		this.description = description;
		this.region = region;
		this.siteGroup = siteGroup;
		this.site = site;
		this.floor = floor;
		this.room = room;
		this.confidentiality = confidentiality;
		this.integrity = integrity;
		this.department = department;
		this.ownerName = ownerName;
		this.serialNumber = serialNumber;
		this.domain = domain;
		this.availability = availability;
		this.primaryCapability = primaryCapability;
	}

	@Id
	@Column(name = "INSTANCE_ID", unique = true, nullable = false, length = 400)
	public String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	@Column(name = "CLASS_NAME", length = 400)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "NAMESPACE_NAME", length = 400)
	public String getNamespaceName() {
		return this.namespaceName;
	}

	public void setNamespaceName(String namespaceName) {
		this.namespaceName = namespaceName;
	}

	@Column(name = "NAME", length = 400)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 400)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "REGION", length = 400)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "SITE_GROUP", length = 400)
	public String getSiteGroup() {
		return this.siteGroup;
	}

	public void setSiteGroup(String siteGroup) {
		this.siteGroup = siteGroup;
	}

	@Column(name = "SITE", length = 400)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "FLOOR", length = 400)
	public String getFloor() {
		return this.floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	@Column(name = "ROOM", length = 400)
	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	@Column(name = "CONFIDENTIALITY", length = 400)
	public String getConfidentiality() {
		return this.confidentiality;
	}

	public void setConfidentiality(String confidentiality) {
		this.confidentiality = confidentiality;
	}

	@Column(name = "INTEGRITY", length = 400)
	public String getIntegrity() {
		return this.integrity;
	}

	public void setIntegrity(String integrity) {
		this.integrity = integrity;
	}

	@Column(name = "DEPARTMENT", length = 400)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "OWNER_NAME", length = 400)
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Column(name = "SERIAL_NUMBER", length = 400)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Column(name = "DOMAIN", length = 400)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "AVAILABILITY", length = 400)
	public String getAvailability() {
		return this.availability;
	}

	public void setAvailability(String availability) {
		this.availability = availability;
	}

	@Column(name = "PRIMARY_CAPABILITY", length = 4000)
	public String getPrimaryCapability() {
		return this.primaryCapability;
	}

	public void setPrimaryCapability(String primaryCapability) {
		this.primaryCapability = primaryCapability;
	}

}
