package com.metricstream.itgrc.atr.dao.vo;

// Generated Apr 30, 2016 1:43:10 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsItgAtrConfigV generated by hbm2java
 */
@Entity
@Table(name = "MS_ITG_ATR_CONFIG_V")
public class MsItgAtrConfigV implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String serverPassword;
	private String username;
	private String arServerUrl;
	private String ddProcessCode;
	private String ddCurrentStage;
	private String ddEnterpriseInfo;
	private String ddEventUserName;
	private String ddCurrentUserName;
	private String ddObjectType;
	private BigDecimal instanceRecNum;
	private BigDecimal instanceId;
	private BigDecimal metricId;
	private Date metricRunDate;
	private Date metricCompletedDate;
	private String latestFlag;
	private BigDecimal createdBy;
	private Date creationDate;
	private BigDecimal processFlowStatus;
	private BigDecimal processInstanceId;
	private String multirowGroupName;
	private BigDecimal electronicallySigned;
	private BigDecimal multirowRegionId;

	public MsItgAtrConfigV() {
	}

	@Column(name = "SERVER_PASSWORD", length = 4000)
	public String getServerPassword() {
		return this.serverPassword;
	}

	public void setServerPassword(String serverPassword) {
		this.serverPassword = serverPassword;
	}

	@Column(name = "USERNAME", length = 4000)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "AR_SERVER_URL", length = 4000)
	public String getArServerUrl() {
		return this.arServerUrl;
	}

	public void setArServerUrl(String arServerUrl) {
		this.arServerUrl = arServerUrl;
	}

	@Column(name = "DD_PROCESS_CODE", length = 4000)
	public String getDdProcessCode() {
		return this.ddProcessCode;
	}

	public void setDdProcessCode(String ddProcessCode) {
		this.ddProcessCode = ddProcessCode;
	}

	@Column(name = "DD_CURRENT_STAGE", length = 4000)
	public String getDdCurrentStage() {
		return this.ddCurrentStage;
	}

	public void setDdCurrentStage(String ddCurrentStage) {
		this.ddCurrentStage = ddCurrentStage;
	}

	@Column(name = "DD_ENTERPRISE_INFO", length = 4000)
	public String getDdEnterpriseInfo() {
		return this.ddEnterpriseInfo;
	}

	public void setDdEnterpriseInfo(String ddEnterpriseInfo) {
		this.ddEnterpriseInfo = ddEnterpriseInfo;
	}

	@Column(name = "DD_EVENT_USER_NAME", length = 4000)
	public String getDdEventUserName() {
		return this.ddEventUserName;
	}

	public void setDdEventUserName(String ddEventUserName) {
		this.ddEventUserName = ddEventUserName;
	}

	@Column(name = "DD_CURRENT_USER_NAME", length = 4000)
	public String getDdCurrentUserName() {
		return this.ddCurrentUserName;
	}

	public void setDdCurrentUserName(String ddCurrentUserName) {
		this.ddCurrentUserName = ddCurrentUserName;
	}

	@Column(name = "DD_OBJECT_TYPE", length = 4000)
	public String getDdObjectType() {
		return this.ddObjectType;
	}

	public void setDdObjectType(String ddObjectType) {
		this.ddObjectType = ddObjectType;
	}

	@Column(name = "INSTANCE_REC_NUM", precision = 22, scale = 0)
	public BigDecimal getInstanceRecNum() {
		return this.instanceRecNum;
	}

	public void setInstanceRecNum(BigDecimal instanceRecNum) {
		this.instanceRecNum = instanceRecNum;
	}

	@Column(name = "INSTANCE_ID", precision = 22, scale = 0)
	public BigDecimal getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(BigDecimal instanceId) {
		this.instanceId = instanceId;
	}

	@Column(name = "METRIC_ID", precision = 22, scale = 0)
	public BigDecimal getMetricId() {
		return this.metricId;
	}

	public void setMetricId(BigDecimal metricId) {
		this.metricId = metricId;
	}

	@Column(name = "METRIC_RUN_DATE", length = 7)
	public Date getMetricRunDate() {
		return this.metricRunDate;
	}

	public void setMetricRunDate(Date metricRunDate) {
		this.metricRunDate = metricRunDate;
	}

	@Column(name = "METRIC_COMPLETED_DATE", length = 7)
	public Date getMetricCompletedDate() {
		return this.metricCompletedDate;
	}

	public void setMetricCompletedDate(Date metricCompletedDate) {
		this.metricCompletedDate = metricCompletedDate;
	}

	@Column(name = "LATEST_FLAG", length = 4)
	public String getLatestFlag() {
		return this.latestFlag;
	}

	public void setLatestFlag(String latestFlag) {
		this.latestFlag = latestFlag;
	}

	@Column(name = "CREATED_BY", precision = 22, scale = 0)
	public BigDecimal getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(BigDecimal createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATION_DATE", length = 7)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "PROCESS_FLOW_STATUS", precision = 22, scale = 0)
	public BigDecimal getProcessFlowStatus() {
		return this.processFlowStatus;
	}

	public void setProcessFlowStatus(BigDecimal processFlowStatus) {
		this.processFlowStatus = processFlowStatus;
	}
	
	@Id
	@Column(name = "PROCESS_INSTANCE_ID", precision = 22, scale = 0)
	public BigDecimal getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(BigDecimal processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	@Column(name = "MULTIROW_GROUP_NAME", length = 400)
	public String getMultirowGroupName() {
		return this.multirowGroupName;
	}

	public void setMultirowGroupName(String multirowGroupName) {
		this.multirowGroupName = multirowGroupName;
	}

	@Column(name = "ELECTRONICALLY_SIGNED", precision = 22, scale = 0)
	public BigDecimal getElectronicallySigned() {
		return this.electronicallySigned;
	}

	public void setElectronicallySigned(BigDecimal electronicallySigned) {
		this.electronicallySigned = electronicallySigned;
	}

	@Column(name = "MULTIROW_REGION_ID", precision = 22, scale = 0)
	public BigDecimal getMultirowRegionId() {
		return this.multirowRegionId;
	}

	public void setMultirowRegionId(BigDecimal multirowRegionId) {
		this.multirowRegionId = multirowRegionId;
	}
}
