package com.metricstream.itgrc.atr.dao.vo;

// Generated Apr 30, 2016 1:55:01 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsItgBmcIpEndpoint generated by hbm2java
 */
@Entity
@Table(name = "MS_ITG_BMC_IP_ENDPOINT")
public class MsItgBmcIpEndpoint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String instanceId;
	private String className;
	private String namespaceName;
	private String addressType;
	private String address;
	private String dnsHostname;

	public MsItgBmcIpEndpoint() {
	}

	public MsItgBmcIpEndpoint(String instanceId) {
		this.instanceId = instanceId;
	}

	public MsItgBmcIpEndpoint(String instanceId, String className,
			String namespaceName, String addressType, String address,
			String dnsHostname) {
		this.instanceId = instanceId;
		this.className = className;
		this.namespaceName = namespaceName;
		this.addressType = addressType;
		this.address = address;
		this.dnsHostname = dnsHostname;
	}

	@Id
	@Column(name = "INSTANCE_ID", unique = true, nullable = false, length = 400)
	public String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	@Column(name = "CLASS_NAME", length = 400)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "NAMESPACE_NAME", length = 400)
	public String getNamespaceName() {
		return this.namespaceName;
	}

	public void setNamespaceName(String namespaceName) {
		this.namespaceName = namespaceName;
	}

	@Column(name = "ADDRESS_TYPE", length = 400)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "ADDRESS", length = 400)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "DNS_HOSTNAME", length = 400)
	public String getDnsHostname() {
		return this.dnsHostname;
	}

	public void setDnsHostname(String dnsHostname) {
		this.dnsHostname = dnsHostname;
	}

}
