package com.metricstream.itgrc.atr.dao.vo;

// Generated Apr 30, 2016 1:52:51 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsItgBmcHostedAccessPoint generated by hbm2java
 */
@Entity
@Table(name = "MS_ITG_BMC_HOSTED_ACCESS_POINT")
public class MsItgBmcHostedAccessPoint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String instanceId;
	private String className;
	private String namespaceName;
	private String name;
	private String sourceInstanceId;
	private String destinationInstanceId;

	public MsItgBmcHostedAccessPoint() {
	}

	public MsItgBmcHostedAccessPoint(String instanceId) {
		this.instanceId = instanceId;
	}

	public MsItgBmcHostedAccessPoint(String instanceId, String className,
			String namespaceName, String name, String sourceInstanceId,
			String destinationInstanceId) {
		this.instanceId = instanceId;
		this.className = className;
		this.namespaceName = namespaceName;
		this.name = name;
		this.sourceInstanceId = sourceInstanceId;
		this.destinationInstanceId = destinationInstanceId;
	}

	@Id
	@Column(name = "INSTANCE_ID", unique = true, nullable = false, length = 100)
	public String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	@Column(name = "CLASS_NAME", length = 100)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "NAMESPACE_NAME", length = 100)
	public String getNamespaceName() {
		return this.namespaceName;
	}

	public void setNamespaceName(String namespaceName) {
		this.namespaceName = namespaceName;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SOURCE_INSTANCE_ID", length = 100)
	public String getSourceInstanceId() {
		return this.sourceInstanceId;
	}

	public void setSourceInstanceId(String sourceInstanceId) {
		this.sourceInstanceId = sourceInstanceId;
	}

	@Column(name = "DESTINATION_INSTANCE_ID", length = 100)
	public String getDestinationInstanceId() {
		return this.destinationInstanceId;
	}

	public void setDestinationInstanceId(String destinationInstanceId) {
		this.destinationInstanceId = destinationInstanceId;
	}

}
