package com.metricstream.itgrc.atr.dao.vo;

// Generated Apr 30, 2016 1:49:38 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsItgBmcAtrMapping generated by hbm2java
 */
@Entity
@Table(name = "MS_ITG_BMC_ATR_MAPPING")
public class MsItgBmcAtrMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String instanceId;
	private String objectId;

	public MsItgBmcAtrMapping() {
	}

	public MsItgBmcAtrMapping(String instanceId) {
		this.instanceId = instanceId;
	}

	public MsItgBmcAtrMapping(String instanceId, String objectId) {
		this.instanceId = instanceId;
		this.objectId = objectId;
	}

	@Id
	@Column(name = "INSTANCE_ID", unique = true, nullable = false, length = 400)
	public String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	@Column(name = "OBJECT_ID", length = 20)
	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

}
