package com.metricstream.itgrc.atr.dao.vo;

// Generated Apr 30, 2016 1:56:59 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsItgBmcLanEndpoint generated by hbm2java
 */
@Entity
@Table(name = "MS_ITG_BMC_LAN_ENDPOINT")
public class MsItgBmcLanEndpoint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String instanceId;
	private String className;
	private String namespaceName;
	private String macaddress;

	public MsItgBmcLanEndpoint() {
	}

	public MsItgBmcLanEndpoint(String instanceId) {
		this.instanceId = instanceId;
	}

	public MsItgBmcLanEndpoint(String instanceId, String className,
			String namespaceName, String macaddress) {
		this.instanceId = instanceId;
		this.className = className;
		this.namespaceName = namespaceName;
		this.macaddress = macaddress;
	}

	@Id
	@Column(name = "INSTANCE_ID", unique = true, nullable = false, length = 400)
	public String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	@Column(name = "CLASS_NAME", length = 400)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "NAMESPACE_NAME", length = 400)
	public String getNamespaceName() {
		return this.namespaceName;
	}

	public void setNamespaceName(String namespaceName) {
		this.namespaceName = namespaceName;
	}

	@Column(name = "MACADDRESS", length = 400)
	public String getMacaddress() {
		return this.macaddress;
	}

	public void setMacaddress(String macaddress) {
		this.macaddress = macaddress;
	}

}
