BEGIN

DELETE FROM MS_ITG_CONFIG_SETUP_INFO WHERE UUID=500000;
DELETE FROM MS_ITG_CONFIG_SETUP WHERE UUID=500000 AND LOCALE_ID=1009;

INSERT INTO MS_ITG_CONFIG_SETUP 
  (
	UUID, MODULE, CONNECTOR_NAME, DESCRIPTION, INSTALLATION_DATE, LOCALE_ID,TYPE
  )
  VALUES 
  (
	500000,'ATR','Atrium','BMC Atrium Web Services Connectivity Configuration', SYSDATE,(SELECT locale_id FROM si_locales WHERE locale_string =
  (SELECT locale FROM si_users_t WHERE user_name = 'SYSTEMI'
  )),'CMBD SOURCE'
  );

  COMMIT;
END; 
 