DECLARE
v_count Number;
BEGIN
Select count(*) into v_count from MS_ITG_BMC_AVAILABILITY_ATTR;
if v_count=0 then
Insert into MS_ITG_BMC_AVAILABILITY_ATTR (CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,AVAILABILTY_STORED_V,AVAILABILITY_DISPLAYED_V) values (100000,to_date('30-APR-16','DD-MON-RR'),100000,to_date('30-APR-16','DD-MON-RR'),10,'(N/A) Indicates no effect');
Insert into MS_ITG_BMC_AVAILABILITY_ATTR (CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,AVAILABILTY_STORED_V,AVAILABILITY_DISPLAYED_V) values (100000,to_date('30-APR-16','DD-MON-RR'),100000,to_date('30-APR-16','DD-MON-RR'),20,'(Low) Indicates limited adverse effects');
Insert into MS_ITG_BMC_AVAILABILITY_ATTR (CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,AVAILABILTY_STORED_V,AVAILABILITY_DISPLAYED_V) values (100000,to_date('30-APR-16','DD-MON-RR'),100000,to_date('30-APR-16','DD-MON-RR'),30,'(Moderate) Indicates serious adverse effects');
Insert into MS_ITG_BMC_AVAILABILITY_ATTR (CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,AVAILABILTY_STORED_V,AVAILABILITY_DISPLAYED_V) values (100000,to_date('30-APR-16','DD-MON-RR'),100000,to_date('30-APR-16','DD-MON-RR'),40,'(High) Indicates severe or catastrophic adverse effects');
end if;
commit;
end;
