//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 02:46:03 PM IST 
//


package com.metricstream.itgrc.cmd.asset.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ASSTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ASSTType">
 *   &lt;complexContent>
 *     &lt;extension base="{}CommonFieldsType">
 *       &lt;sequence>
 *         &lt;element name="asset_object_level" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="asset_object_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="asset_object_parent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="physical_location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="business_criticality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="confidentiality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="integrity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="availability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="net_bios_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dns_name_fqdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mac_address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ipv4_address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ipv6_address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recovery_time_objective_rto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recovery_point_objective_rpo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="work_recovery_time_wrt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maximum_tolerable_downtime_mtd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recovery_time_actual_rta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="duration_rto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="duration_rpo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="duration_wrt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="duration_mtd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="duration_rta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="relationships" type="{}RelationshipType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ASSTType", propOrder = {
    "assetObjectLevel",
    "assetObjectType",
    "assetObjectParent",
    "physicalLocation",
    "businessCriticality",
    "confidentiality",
    "integrity",
    "availability",
    "serial",
    "netBiosName",
    "dnsNameFqdn",
    "macAddress",
    "ipv4Address",
    "ipv6Address",
    "recoveryTimeObjectiveRto",
    "recoveryPointObjectiveRpo",
    "workRecoveryTimeWrt",
    "maximumTolerableDowntimeMtd",
    "recoveryTimeActualRta",
    "durationRto",
    "durationRpo",
    "durationWrt",
    "durationMtd",
    "durationRta",
    "status",
    "relationships"
})
public class ASSTType
    extends CommonFieldsType
{

    @XmlElement(name = "asset_object_level")
    protected String assetObjectLevel;
    @XmlElement(name = "asset_object_type")
    protected String assetObjectType;
    @XmlElement(name = "asset_object_parent")
    protected String assetObjectParent;
    @XmlElement(name = "physical_location")
    protected String physicalLocation;
    @XmlElement(name = "business_criticality")
    protected String businessCriticality;
    protected String confidentiality;
    protected String integrity;
    protected String availability;
    protected String serial;
    @XmlElement(name = "net_bios_name")
    protected String netBiosName;
    @XmlElement(name = "dns_name_fqdn")
    protected String dnsNameFqdn;
    @XmlElement(name = "mac_address")
    protected String macAddress;
    @XmlElement(name = "ipv4_address")
    protected String ipv4Address;
    @XmlElement(name = "ipv6_address")
    protected String ipv6Address;
    @XmlElement(name = "recovery_time_objective_rto")
    protected String recoveryTimeObjectiveRto;
    @XmlElement(name = "recovery_point_objective_rpo")
    protected String recoveryPointObjectiveRpo;
    @XmlElement(name = "work_recovery_time_wrt")
    protected String workRecoveryTimeWrt;
    @XmlElement(name = "maximum_tolerable_downtime_mtd")
    protected String maximumTolerableDowntimeMtd;
    @XmlElement(name = "recovery_time_actual_rta")
    protected String recoveryTimeActualRta;
    @XmlElement(name = "duration_rto")
    protected String durationRto;
    @XmlElement(name = "duration_rpo")
    protected String durationRpo;
    @XmlElement(name = "duration_wrt")
    protected String durationWrt;
    @XmlElement(name = "duration_mtd")
    protected String durationMtd;
    @XmlElement(name = "duration_rta")
    protected String durationRta;
    protected String status;
    protected RelationshipType relationships;

    /**
     * Gets the value of the assetObjectLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetObjectLevel() {
        return assetObjectLevel;
    }

    /**
     * Sets the value of the assetObjectLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetObjectLevel(String value) {
        this.assetObjectLevel = value;
    }

    /**
     * Gets the value of the assetObjectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetObjectType() {
        return assetObjectType;
    }

    /**
     * Sets the value of the assetObjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetObjectType(String value) {
        this.assetObjectType = value;
    }

    /**
     * Gets the value of the assetObjectParent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetObjectParent() {
        return assetObjectParent;
    }

    /**
     * Sets the value of the assetObjectParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetObjectParent(String value) {
        this.assetObjectParent = value;
    }

    /**
     * Gets the value of the physicalLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicalLocation() {
        return physicalLocation;
    }

    /**
     * Sets the value of the physicalLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalLocation(String value) {
        this.physicalLocation = value;
    }

    /**
     * Gets the value of the businessCriticality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessCriticality() {
        return businessCriticality;
    }

    /**
     * Sets the value of the businessCriticality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessCriticality(String value) {
        this.businessCriticality = value;
    }

    /**
     * Gets the value of the confidentiality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfidentiality() {
        return confidentiality;
    }

    /**
     * Sets the value of the confidentiality property.
     * 
     * @param i
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidentiality(String confidentiality) {
        this.confidentiality = confidentiality;
    }

    /**
     * Gets the value of the integrity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegrity() {
        return integrity;
    }

    /**
     * Sets the value of the integrity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegrity(String value) {
        this.integrity = value;
    }

    /**
     * Gets the value of the availability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailability() {
        return availability;
    }

    /**
     * Sets the value of the availability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailability(String value) {
        this.availability = value;
    }

    /**
     * Gets the value of the serial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerial() {
        return serial;
    }

    /**
     * Sets the value of the serial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerial(String value) {
        this.serial = value;
    }

    /**
     * Gets the value of the netBiosName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetBiosName() {
        return netBiosName;
    }

    /**
     * Sets the value of the netBiosName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetBiosName(String value) {
        this.netBiosName = value;
    }

    /**
     * Gets the value of the dnsNameFqdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnsNameFqdn() {
        return dnsNameFqdn;
    }

    /**
     * Sets the value of the dnsNameFqdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnsNameFqdn(String value) {
        this.dnsNameFqdn = value;
    }

    /**
     * Gets the value of the macAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMacAddress() {
        return macAddress;
    }

    /**
     * Sets the value of the macAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMacAddress(String value) {
        this.macAddress = value;
    }

    /**
     * Gets the value of the ipv4Address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpv4Address() {
        return ipv4Address;
    }

    /**
     * Sets the value of the ipv4Address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpv4Address(String value) {
        this.ipv4Address = value;
    }

    /**
     * Gets the value of the ipv6Address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpv6Address() {
        return ipv6Address;
    }

    /**
     * Sets the value of the ipv6Address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpv6Address(String value) {
        this.ipv6Address = value;
    }

    /**
     * Gets the value of the recoveryTimeObjectiveRto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecoveryTimeObjectiveRto() {
        return recoveryTimeObjectiveRto;
    }

    /**
     * Sets the value of the recoveryTimeObjectiveRto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecoveryTimeObjectiveRto(String value) {
        this.recoveryTimeObjectiveRto = value;
    }

    /**
     * Gets the value of the recoveryPointObjectiveRpo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecoveryPointObjectiveRpo() {
        return recoveryPointObjectiveRpo;
    }

    /**
     * Sets the value of the recoveryPointObjectiveRpo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecoveryPointObjectiveRpo(String value) {
        this.recoveryPointObjectiveRpo = value;
    }

    /**
     * Gets the value of the workRecoveryTimeWrt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkRecoveryTimeWrt() {
        return workRecoveryTimeWrt;
    }

    /**
     * Sets the value of the workRecoveryTimeWrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkRecoveryTimeWrt(String value) {
        this.workRecoveryTimeWrt = value;
    }

    /**
     * Gets the value of the maximumTolerableDowntimeMtd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumTolerableDowntimeMtd() {
        return maximumTolerableDowntimeMtd;
    }

    /**
     * Sets the value of the maximumTolerableDowntimeMtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumTolerableDowntimeMtd(String value) {
        this.maximumTolerableDowntimeMtd = value;
    }

    /**
     * Gets the value of the recoveryTimeActualRta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecoveryTimeActualRta() {
        return recoveryTimeActualRta;
    }

    /**
     * Sets the value of the recoveryTimeActualRta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecoveryTimeActualRta(String value) {
        this.recoveryTimeActualRta = value;
    }

    /**
     * Gets the value of the durationRto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationRto() {
        return durationRto;
    }

    /**
     * Sets the value of the durationRto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationRto(String value) {
        this.durationRto = value;
    }

    /**
     * Gets the value of the durationRpo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationRpo() {
        return durationRpo;
    }

    /**
     * Sets the value of the durationRpo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationRpo(String value) {
        this.durationRpo = value;
    }

    /**
     * Gets the value of the durationWrt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationWrt() {
        return durationWrt;
    }

    /**
     * Sets the value of the durationWrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationWrt(String value) {
        this.durationWrt = value;
    }

    /**
     * Gets the value of the durationMtd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationMtd() {
        return durationMtd;
    }

    /**
     * Sets the value of the durationMtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationMtd(String value) {
        this.durationMtd = value;
    }

    /**
     * Gets the value of the durationRta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationRta() {
        return durationRta;
    }

    /**
     * Sets the value of the durationRta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationRta(String value) {
        this.durationRta = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the relationships property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipType }
     *     
     */
    public RelationshipType getRelationships() {
        return relationships;
    }

    /**
     * Sets the value of the relationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipType }
     *     
     */
    public void setRelationships(RelationshipType value) {
        this.relationships = value;
    }

}
