
package com.bmc.atrium._2009._01.instances;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "atrium_instances", targetNamespace = "http://atrium.bmc.com/2009/01/instances", wsdlLocation = "https://vmidevmercitgrc.metricstream.com:8443/atriumws91/services/atrium_instances.wsdl")
//@WebServiceClient(name = "atrium_instances", targetNamespace = "http://atrium.bmc.com/2009/01/instances", wsdlLocation = "https://182.71.249.231:8443/atriumws91/services/atrium_instances.wsdl")
public class AtriumInstances
    extends Service
{

    private final static URL ATRIUMINSTANCES_WSDL_LOCATION;
    private final static WebServiceException ATRIUMINSTANCES_EXCEPTION;
    private final static QName ATRIUMINSTANCES_QNAME = new QName("http://atrium.bmc.com/2009/01/instances", "atrium_instances");

    static {
        URL url = null;
        WebServiceException e = null;
        
        try {
            url = new URL("https://vmidevmercitgrc.metricstream.com:8443/atriumws91/services/atrium_instances.wsdl");
//            url = new URL("https://182.71.249.231:8443/atriumws91/services/atrium_instances.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATRIUMINSTANCES_WSDL_LOCATION = url;
        ATRIUMINSTANCES_EXCEPTION = e;
    }

    public AtriumInstances() {
        super(__getWsdlLocation(), ATRIUMINSTANCES_QNAME);
    }

    public AtriumInstances(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATRIUMINSTANCES_QNAME, features);
    }

    public AtriumInstances(URL wsdlLocation) {
        super(wsdlLocation, ATRIUMINSTANCES_QNAME);
    }

    public AtriumInstances(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATRIUMINSTANCES_QNAME, features);
    }

    public AtriumInstances(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AtriumInstances(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AtriumInstancesPortType
     */
    @WebEndpoint(name = "AtriumInstances_WebService")
    public AtriumInstancesPortType getAtriumInstancesWebService() {
        return super.getPort(new QName("http://atrium.bmc.com/2009/01/instances", "AtriumInstances_WebService"), AtriumInstancesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AtriumInstancesPortType
     */
    @WebEndpoint(name = "AtriumInstances_WebService")
    public AtriumInstancesPortType getAtriumInstancesWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://atrium.bmc.com/2009/01/instances", "AtriumInstances_WebService"), AtriumInstancesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATRIUMINSTANCES_EXCEPTION!= null) {
            throw ATRIUMINSTANCES_EXCEPTION;
        }
        return ATRIUMINSTANCES_WSDL_LOCATION;
    }

}
