
package com.bmc.atrium._2009._01.instances;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.bmc.atrium._2009._01.common.ClassNameId;
import com.bmc.atrium._2009._01.common.ExtensionList;
import com.bmc.atrium._2009._01.common.GetMask;
import com.bmc.atrium._2009._01.common.InstanceInfoOutList;
import com.bmc.atrium._2009._01.common.LoginInfo;
import com.bmc.atrium._2009._01.common.StatusList;
import com.bmc.atrium._2009._01.common.StringArray;
import com.bmc.atrium._2009._01.instances.types.AuditValueListList;
import com.bmc.atrium._2009._01.instances.types.CreateInstanceInfoIn;
import com.bmc.atrium._2009._01.instances.types.CreateInstanceInfoInList;
import com.bmc.atrium._2009._01.instances.types.DeleteInstanceInfoIn;
import com.bmc.atrium._2009._01.instances.types.DeleteInstanceInfoInList;
import com.bmc.atrium._2009._01.instances.types.InstanceDeleteOption;
import com.bmc.atrium._2009._01.instances.types.SetInstanceInfoIn;
import com.bmc.atrium._2009._01.instances.types.SetInstanceInfoInList;
import com.bmc.atrium._2009._01.instances.types.SortOrderList;
import com.bmc.atrium._2009._01.instances.types.UIComponentInfo;
import com.bmc.atrium._2009._01.instances.types.UIComponentResultList;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AtriumInstances_PortType", targetNamespace = "http://atrium.bmc.com/2009/01/instances")
@XmlSeeAlso({
    com.bmc.atrium._2009._01.common.ObjectFactory.class,
    com.bmc.atrium._2009._01.instances.types.ObjectFactory.class
})
public interface AtriumInstancesPortType {


    /**
     * 
     * @param instanceIds
     * @param instanceInfo
     * @param status
     * @param datasetId
     * @param loginInfo
     * @param extensions
     * @throws AtriumFault
     */
    @WebMethod(operationName = "CreateMultipleInstances", action = "CreateMultipleInstances")
    @RequestWrapper(localName = "CreateMultipleInstances", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.CreateMultipleInstances")
    @ResponseWrapper(localName = "CreateMultipleInstancesOutput", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.CreateMultipleInstancesOutput")
    public void createMultipleInstances(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "datasetId", targetNamespace = "")
        String datasetId,
        @WebParam(name = "instanceInfo", targetNamespace = "")
        CreateInstanceInfoInList instanceInfo,
        @WebParam(name = "extensions", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<ExtensionList> extensions,
        @WebParam(name = "instanceIds", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StringArray> instanceIds,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StatusList> status)
        throws AtriumFault
    ;

    /**
     * 
     * @param auditValueListList
     * @param status
     * @param classNameId
     * @param query
     * @param datasetId
     * @param loginInfo
     * @param instanceId
     * @param attributes
     * @param extensions
     * @throws AtriumFault
     */
    @WebMethod(operationName = "GetCopyAuditData", action = "GetCopyAuditData")
    @RequestWrapper(localName = "GetCopyAuditData", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.GetCopyAuditData")
    @ResponseWrapper(localName = "GetCopyAuditDataOutput", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.GetCopyAuditDataOutput")
    public void getCopyAuditData(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "classNameId", targetNamespace = "")
        ClassNameId classNameId,
        @WebParam(name = "instanceId", targetNamespace = "")
        String instanceId,
        @WebParam(name = "datasetId", targetNamespace = "")
        String datasetId,
        @WebParam(name = "query", targetNamespace = "")
        String query,
        @WebParam(name = "attributes", targetNamespace = "")
        StringArray attributes,
        @WebParam(name = "extensions", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<ExtensionList> extensions,
        @WebParam(name = "auditValueListList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<AuditValueListList> auditValueListList,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StatusList> status)
        throws AtriumFault
    ;

    /**
     * 
     * @param instanceInfo
     * @param status
     * @param datasetId
     * @param loginInfo
     * @param instanceId
     * @param extensions
     * @throws AtriumFault
     */
    @WebMethod(operationName = "CreateInstance", action = "CreateInstance")
    @RequestWrapper(localName = "CreateInstance", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.CreateInstance")
    @ResponseWrapper(localName = "CreateInstanceOutput", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.CreateInstanceOutput")
    public void createInstance(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "datasetId", targetNamespace = "")
        String datasetId,
        @WebParam(name = "instanceInfo", targetNamespace = "")
        CreateInstanceInfoIn instanceInfo,
        @WebParam(name = "extensions", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<ExtensionList> extensions,
        @WebParam(name = "instanceId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> instanceId,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StatusList> status)
        throws AtriumFault
    ;

    /**
     * 
     * @param instanceInfo
     * @param status
     * @param datasetId
     * @param loginInfo
     * @param extensions
     * @throws AtriumFault
     */
    @WebMethod(operationName = "SetMultipleInstances", action = "SetMultipleInstances")
    @RequestWrapper(localName = "SetMultipleInstances", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.SetMultipleInstances")
    @ResponseWrapper(localName = "StatusOutput", targetNamespace = "http://atrium.bmc.com/2009/01/common", className = "com.bmc.atrium._2009._01.common.StatusOutput")
    public void setMultipleInstances(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "datasetId", targetNamespace = "")
        String datasetId,
        @WebParam(name = "instanceInfo", targetNamespace = "")
        SetInstanceInfoInList instanceInfo,
        @WebParam(name = "extensions", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<ExtensionList> extensions,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StatusList> status)
        throws AtriumFault
    ;

    /**
     * 
     * @param instanceInfo
     * @param status
     * @param datasetId
     * @param loginInfo
     * @param deleteOption
     * @param extensions
     * @throws AtriumFault
     */
    @WebMethod(operationName = "DeleteInstance", action = "DeleteInstance")
    @RequestWrapper(localName = "DeleteInstance", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.DeleteInstance")
    @ResponseWrapper(localName = "StatusOutput", targetNamespace = "http://atrium.bmc.com/2009/01/common", className = "com.bmc.atrium._2009._01.common.StatusOutput")
    public void deleteInstance(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "datasetId", targetNamespace = "")
        String datasetId,
        @WebParam(name = "instanceInfo", targetNamespace = "")
        DeleteInstanceInfoIn instanceInfo,
        @WebParam(name = "deleteOption", targetNamespace = "")
        InstanceDeleteOption deleteOption,
        @WebParam(name = "extensions", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<ExtensionList> extensions,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StatusList> status)
        throws AtriumFault
    ;

    /**
     * 
     * @param getMask
     * @param instanceInfo
     * @param status
     * @param classNameId
     * @param sortOrder
     * @param query
     * @param datasetId
     * @param loginInfo
     * @param firstRetrieve
     * @param attributes
     * @param extensions
     * @param maxRetrieve
     * @throws AtriumFault
     */
    @WebMethod(operationName = "GetInstances", action = "GetInstances")
    @RequestWrapper(localName = "GetInstances", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.GetInstances")
    @ResponseWrapper(localName = "GetInstancesOutput", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.GetInstancesOutput")
    public void getInstances(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "classNameId", targetNamespace = "")
        ClassNameId classNameId,
        @WebParam(name = "query", targetNamespace = "")
        String query,
        @WebParam(name = "attributes", targetNamespace = "")
        StringArray attributes,
        @WebParam(name = "firstRetrieve", targetNamespace = "")
        int firstRetrieve,
        @WebParam(name = "maxRetrieve", targetNamespace = "")
        int maxRetrieve,
        @WebParam(name = "sortOrder", targetNamespace = "")
        SortOrderList sortOrder,
        @WebParam(name = "datasetId", targetNamespace = "")
        String datasetId,
        @WebParam(name = "getMask", targetNamespace = "")
        GetMask getMask,
        @WebParam(name = "extensions", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<ExtensionList> extensions,
        @WebParam(name = "instanceInfo", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<InstanceInfoOutList> instanceInfo,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StatusList> status)
        throws AtriumFault
    ;

    /**
     * 
     * @param uiComponentResultList
     * @param status
     * @param componentInfo
     * @param datasetId
     * @param loginInfo
     * @param instanceId
     * @param extensions
     * @throws AtriumFault
     */
    @WebMethod(operationName = "GetUIComponents", action = "GetUIComponents")
    @RequestWrapper(localName = "GetUIComponents", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.GetUIComponents")
    @ResponseWrapper(localName = "GetUIComponentsOutput", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.GetUIComponentsOutput")
    public void getUIComponents(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "componentInfo", targetNamespace = "")
        UIComponentInfo componentInfo,
        @WebParam(name = "datasetId", targetNamespace = "")
        String datasetId,
        @WebParam(name = "instanceId", targetNamespace = "")
        String instanceId,
        @WebParam(name = "extensions", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<ExtensionList> extensions,
        @WebParam(name = "uiComponentResultList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<UIComponentResultList> uiComponentResultList,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StatusList> status)
        throws AtriumFault
    ;

    /**
     * 
     * @param instanceInfo
     * @param status
     * @param datasetId
     * @param loginInfo
     * @param extensions
     * @throws AtriumFault
     */
    @WebMethod(operationName = "SetInstance", action = "SetInstance")
    @RequestWrapper(localName = "SetInstance", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.SetInstance")
    @ResponseWrapper(localName = "StatusOutput", targetNamespace = "http://atrium.bmc.com/2009/01/common", className = "com.bmc.atrium._2009._01.common.StatusOutput")
    public void setInstance(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "datasetId", targetNamespace = "")
        String datasetId,
        @WebParam(name = "instanceInfo", targetNamespace = "")
        SetInstanceInfoIn instanceInfo,
        @WebParam(name = "extensions", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<ExtensionList> extensions,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StatusList> status)
        throws AtriumFault
    ;

    /**
     * 
     * @param instanceInfo
     * @param status
     * @param datasetId
     * @param loginInfo
     * @param deleteOption
     * @param extensions
     * @throws AtriumFault
     */
    @WebMethod(operationName = "DeleteMultipleInstances", action = "DeleteMultipleInstances")
    @RequestWrapper(localName = "DeleteMultipleInstances", targetNamespace = "http://atrium.bmc.com/2009/01/instances/types", className = "com.bmc.atrium._2009._01.instances.types.DeleteMultipleInstances")
    @ResponseWrapper(localName = "StatusOutput", targetNamespace = "http://atrium.bmc.com/2009/01/common", className = "com.bmc.atrium._2009._01.common.StatusOutput")
    public void deleteMultipleInstances(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "datasetId", targetNamespace = "")
        String datasetId,
        @WebParam(name = "instanceInfo", targetNamespace = "")
        DeleteInstanceInfoInList instanceInfo,
        @WebParam(name = "deleteOption", targetNamespace = "")
        InstanceDeleteOption deleteOption,
        @WebParam(name = "extensions", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<ExtensionList> extensions,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StatusList> status)
        throws AtriumFault
    ;

}
